// AUTO-GENERATED by scripts/apply-buyer-preset.mjs — 2026-04-17T07:38:48.857Z
// Buyer: XYZ Financial
// Preset: buyers/xyz-financial/config.json
// To regenerate: node scripts/apply-buyer-preset.mjs buyers/xyz-financial/config.json

const branchConfig = {
  // Branding
  appName:         'XYZ Financial Advisor',
  logo:             require('./assets/icon.png'),
  primaryColor:    '#1D4ED8',
  backgroundColor: '#0F172A',

  // Branch identity
  branchName: 'XYZ Financial',
  agentName:  'Jordan Reyes',
  location:   '88 Commerce Blvd, Suite 400, Manila, PH 1000',
  phone:      '+63 2 8000 0000',
  email:      'jordan.reyes@xyzfinancial.ph',

  // Scheduling & contact
  calendlyUrl:     'https://calendly.com/jordan-reyes-xyz',
  messengerPageId: '100094123456789',

  // Integrations
  n8nWebhook:      'https://n8n.xyzfinancial.ph/webhook/leads',
  googleSheetsKey: 'AIzaSyXYZFinancialDummyKey1234567890',
  appsScriptUrl:   'https://script.google.com/macros/s/XYZFinancialScriptId/exec',

  // WebView URLs
  webviewUrl:    'https://www.prubsq.com',
  assessmentUrl: 'https://www.prubsq.com/assessment',
  resultsUrl:    'https://www.prubsq.com/results',

  // Store / build
  bundleId:         'com.xyzfinancial.advisorai',
  androidPackage:   'com.xyzfinancial.advisorai',
  privacyPolicyUrl: 'https://www.xyzfinancial.ph/privacy',
  supportUrl:       'https://www.xyzfinancial.ph/support',
};

export default branchConfig;
